spring.application.name=user-service

server.port=8081

# Hibernate common settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

# Enable SQL script initialization for all database types
spring.sql.init.mode=always

# Defer initialization so it runs AFTER Hibernate creates the tables
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
logging.level.org.springframework.security=DEBUG

logging.level.org.springframework.jdbc.datasource.init=DEBUG
logging.level.org.hibernate.SQL=DEBUG

#Eureka client
#eureka.client.service-url.default-zone=http://localhost:8761/eureka/
#eureka.instance.prefer-ip-address=true
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true


