# H2 Database (in-memory)
spring.datasource.url=jdbc:h2:mem:userservice
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#spring.security.user.name=admin
#spring.security.user.password=admin

# Enable H2 Console (optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate dialect for H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Log SQL execution
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Log data.sql execution
logging.level.org.springframework.jdbc.datasource.init=DEBUG
